// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9JCdZs2WvRUtbXmWU4Fn3TaRty82b6HY',
    appId: '1:246040457998:web:8f52b30002a3af39e29d5f',
    messagingSenderId: '246040457998',
    projectId: 'conectask-a7fab',
    authDomain: 'conectask-a7fab.firebaseapp.com',
    databaseURL: 'https://conectask-a7fab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'conectask-a7fab.firebasestorage.app',
    measurementId: 'G-E3HE4VMSYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeeev9Nnz5K2-IfcFDyBZ09lq_ZlHhAaY',
    appId: '1:246040457998:android:c9c2d0fbc69a12c8e29d5f',
    messagingSenderId: '246040457998',
    projectId: 'conectask-a7fab',
    databaseURL: 'https://conectask-a7fab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'conectask-a7fab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbtO2b87thWvl6RKHI1Nj9erx5iQVO8w',
    appId: '1:246040457998:ios:c8895f25e02beea0e29d5f',
    messagingSenderId: '246040457998',
    projectId: 'conectask-a7fab',
    databaseURL: 'https://conectask-a7fab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'conectask-a7fab.firebasestorage.app',
    iosBundleId: 'com.example.conectaskV2',
  );
}
